[[link]]
name = "The Flash Games Postmortem"
author = "John Cooney (jmtb02)"
link = "https://www.youtube.com/watch?v=65crLKNQR0E"
commentary = "John does a better job than I ever could recounting the Flash games scene. At 9:45 he tells the story of how he had to ride his bike to school to build a particularly large Flash game. I remember him talking about that in the NG forums. It was for Four Second Firestorm if I'm remembering correctly."

[[link]]
name = "The Flash game movement, my early Flash work, and how Flash games informed what we have in indie games today"
author = "Nathalie Lawhead (alienmelon)"
link = "http://www.nathalielawhead.com/candybox/the-flash-game-movement-my-early-flash-work-and-how-flash-games-informed-what-we-have-in-indie-games-today"
commentary = "Nathalie writes about Flash websites and games while weaving in their personal story in a way I wish I could. Their Flash work is way better than mine ever was too."

[[link]]
name = "Flash Changed How We Communicate"
author = "Tom Green"
link = "https://tomgreen17.medium.com/flash-changed-how-we-communicate-56e18a9cdecf"
commentary = "Tom walks through the history of Flash (focusing more on websites and art than games) with a depth of in person recollection that I was too young to have. He also dedicates a section to Hillman Curtis, whose book I flipped through before sitting down to design this page."

[[link]]
name = "An ode to Adobe Flash, and how it saved my future"
author = "Jez Corden"
link = "https://www.windowscentral.com/ode-adobe-flash-and-how-it-saved-my-future"
commentary = "Jez talks about how Flash launched many careers including his own. I too got my start in Flash. I even chose a graphic design path in high school (instead of programming and networking) because it seemed like a better way to level up my Flash aspirations."
